### ISSUE TITLE
Date and 'polymorphic' class causes JsonGenerationException: BsonSerializer can only be used with BsonGenerator

### ISSUE THREAD

**Issue by lovef** [michel-kraemer/bson4jackson#72]
I got an issue when updating to Jongo 1.3.0 that seems to be related to https://github.com/michel-kraemer/bson4jackson/issues/67, I've created a question here: www.stackoverflow.com/questions/42004332/date-and-polymorphic-class-causes-jsongenerationexception-bsonserializer-can

Once again it seems that the order of the properties causes the issue and I only see the problem with java.util.Date. bson4jackson/2.8.0-SNAPSHOT gave a different problem, also described in the SO post.

**Comment by henockteffera** [comment]
Did you find a solution to this problem? We are facing exactly the same issue and using de.undercouch:bson4jackson:2.8.0-SNAPSHOT doesn't solve it.

**Comment by lovef** [comment]
Nope, sorry. We have no good workaround, and as you say, 2.8.0-SNAPSHOT didn't work either, it gave a different problem.

**Comment by henockteffera** [comment]
Thank you lovef for the prompt response.

**Comment by sepatel** [comment]
It should be noted that while it may not have fixed up lovef's issue, the snapshot version of the code does fix a few different issues related to Serialization that is impacting numerous people. Currently I am having to toss out the snapshot version of this code onto a production environment as a result and am wondering if it might not be possible for you to actually cut a release (preferably upgrading your dependency to jackson 2.8.7 or newer as that is what I have confirmed everything to work with including dates)

BTW, if somebody could explain what the "different problem" is, it might be helpful to understanding how to address it as everything I can tell is that the SNAPSHOT version of the code is working perfectly.

**Comment by lovef** [comment]
From the SO post linked above: When I try de.undercouch:bson4jackson:2.8.0-SNAPSHOT the parsed date will be null if it comes after type

I can also include the failing spock test here, it confirms that 2.8.7 does not solve the problem:
```groovy
def mapper = new ObjectMapper(new BsonFactory()).registerModule(new BsonModule())
def bytes = mapper.writeValueAsBytes(original)

expect:
def parsed = mapper.readValue(bytes, Base)
parsed instanceof A // com.fasterxml.jackson.core.JsonGenerationException: BsonSerializer can only be used with BsonGenerator
parsed.string == original.string
parsed.date == original.date // parsed.date is null with 'de.undercouch:bson4jackson:2.8.0-SNAPSHOT'
parsed.type == original.type

where:
testCase                  | original
'A'                       | new A(string: 'string', date: new Date(), type: 'a') // fails
'String, Date, Type'      | [string: 'string', date: new Date(), type: 'a']      // fails
'String, null date, Type' | [string: 'string', date: null, type: 'a']
'String, Type, Date'      | [string: 'string', type: 'a', date: new Date()]
'Type, String, Date'      | [type: 'a', string: 'string', date: new Date()]
```

* `de.undercouch:bson4jackson:2.7.0` (bundled with jongo 1.3) will cause the failing cases above to throw an exception: "BsonSerializer can only be used with BsonGenerator"
* `de.undercouch:bson4jackson:2.8.0-SNAPSHOT` will set date as null in the failing cases

Wether you release the snapshot or not makes no difference to me as I can't update until this issue is resolved.

**Comment by sepatel** [comment]
Interesting because that scenario you outlined works just fine using latest snapshot release which uses the bson4jackson 2.8.0-SNAPSHOT dependency under Java8 (openjdk). And with 2.7.0 it was failing (not even being able to serialize the object to start with).

Could the problem be with Jongo maybe? Even a quick test of code below seems to be handling the data correctly now where as before it was not. Pasted entire codebase so please verify if I am misunderstanding the scenario somehow.

```kotlin
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.ObjectMapper
import de.undercouch.bson4jackson.BsonModule
import org.bson.Document
import org.litote.kmongo.KMongo
import java.util.*

abstract class Base {
    var string: String = ""
    var date: Date? = null
    var type: String = ""
}
class Transform : Base() {
    init {
        type = "c"
    }
}

fun main(args: Array<String>) {
    val mapper = ObjectMapper()
            .registerModule(BsonModule())
            .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)

    val client = KMongo.createClient("localhost")
    val db = client.getDatabase("test")

    val raw = db.getCollection("transform")
    raw.drop() // remove previous data
    raw.insertOne(Document("string", "string").append("date", Date()).append("type", "a"))
    raw.insertOne(Document("string", "string").append("date", null).append("type", "a").append("extra", "stuff"))
    raw.insertOne(Document("string", "string").append("type", "a").append("extra", "stuff"))
    raw.insertOne(Document("string", "string").append("type", "a").append("date", Date()))
    raw.insertOne(Document("type", "a").append("string", "string").append("date", Date()).append("extra", "stuff"))
    raw.insertOne(Document("type", "a").append("string", "string").append("extra", "stuff"))

    raw.find().forEach {
        val bytes = mapper.writeValueAsBytes(it)
        val doc = mapper.readValue(bytes, Transform::class.java)
        println("String: ${doc.string}, Date: ${doc.date}, Type: ${doc.type}")
    }
}
```

With 2.7.0

> Exception in thread "main" com.fasterxml.jackson.core.JsonGenerationException: BsonSerializer can only be used with BsonGenerator


With 2.8.0-SNAPSHOT

> String: string, Date: Fri Mar 31 10:22:13 EDT 2017, Type: a
> String: string, Date: null, Type: a
> String: string, Date: null, Type: a
> String: string, Date: Fri Mar 31 10:22:13 EDT 2017, Type: a
> String: string, Date: Fri Mar 31 10:22:13 EDT 2017, Type: a
> String: string, Date: null, Type: a

**Comment by lovef** [comment]
I updated my example to include the objects to serialize. The key part is the `@JsonTypeInfo` annotations. Not that I read the `Base` type but expect an instance of subclass `A`, based on the type info.

When I run your example, slightly modified as I have no local Mongo DB, I don't get an exception before I added the annotation on the Base class. Strangely I get no error when date is *before* type like in my example, but a new error instead when date comes *after* type:

> Document{{string=string, type=a, date=Mon Apr 03 13:40:50 CEST 2017}}
> 
> com.fasterxml.jackson.databind.JsonMappingException: java.util.Date cannot be cast to java.lang.Number (through reference chain: bsonkotlin.SepatelBsonTest$Transform["date"])

```kotlin
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME,
            include = JsonTypeInfo.As.EXISTING_PROPERTY,
            property = "type",
            visible = true)
    @JsonSubTypes(
        JsonSubTypes.Type(name = "a", value = Transform::class)
    )
    abstract class Base {
        var string: String = ""
        var date: Date? = null
        var type: String = ""
    }

    class Transform : Base() {
        init {
            type = "c"
        }
    }

    @Test fun main() {
        val mapper = ObjectMapper(BsonFactory())
                .registerModule(BsonModule())
                .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)

        val raw = ArrayList<Document>()
        raw.add(Document("string", "string").append("date", Date()).append("type", "a"))
        raw.add(Document("string", "string").append("date", null).append("type", "a").append("extra", "stuff"))
        raw.add(Document("string", "string").append("type", "a").append("extra", "stuff"))
        raw.add(Document("string", "string").append("type", "a").append("date", Date()))
        raw.add(Document("type", "a").append("string", "string").append("date", Date()).append("extra", "stuff"))
        raw.add(Document("type", "a").append("string", "string").append("extra", "stuff"))

        raw.forEach {
            println(it.toString())
            val bytes = mapper.writeValueAsBytes(it)
            val doc = mapper.readValue(bytes, Transform::class.java)
            println("String: ${doc.string}, Date: ${doc.date}, Type: ${doc.type}")

            Assert.assertTrue(doc is Transform)
            Assert.assertEquals(it["string"], doc.string)
            Assert.assertEquals(it["date"], doc.date)
            Assert.assertEquals(it["type"], doc.type)
        }
    }
```

**Comment by sepatel** [comment]
Ok there is definitely something odd going on. After some playing around, it only happens when the BsonModule is enabled (make sense because that is the bson4jackson library and thus the reason this topic is here). And only happens whenever a "date" value is specified after a dynamic property (in the examples above that would be the "type" field.

Would seem like this particular issue is still an issue, however, all the other "BsonSerializer can only be used with BsonGenerator" sources of errors have been resolved. I would like to see a release cut and a stap at a .1 bugfix release to resolve this particular issue if possible.

**Comment by ced-b** [comment]
I am experiencing the same issue with a date which is followed by a dynamically created `_class` attribute.

**Comment by michel-kraemer** [comment]
I just released bson4jackson 2.8.0 (depending on Jackson 2.8.11). Could someone please confirm that the problem still exists with this version? Thanks!

**Comment by lovef** [comment]
Yes, the problem remains.

I also noted now that the behavior is different depending on what BsonModule is used. I've been using the one from Jongo which extends the one from bson4jackson

`org.jongo.marshall.jackson.bson4jackson.BsonModule`
`de.undercouch.bson4jackson.BsonModule`

Using the bson4jackson version yields a different result: If the date comes last then we get `com.fasterxml.jackson.databind.JsonMappingException: java.util.Date cannot be cast to java.lang.Number (through reference chain: A["date"])`

```groovy
[date: new Date(), type: 'a']         // Works (with de.undercouch.bson4jackson.BsonModule)
[type: 'a',        date: new Date()]  // Fails
```

Just about the opposite from the Jongo module which fails on the first (date being parsed as null).

**Comment by etrochim** [comment]
I've just encountered this same issue with jongo 1.4.0 (which includes bson4jackson 2.9.0) and jackson 2.9.7.  Does a workaround exist?

**Comment by fcamblor** [comment]
@etrochim I met it on restx as well (see https://github.com/restx/restx/issues/285)

Currently waiting for a `jongo@1.4.1` release rolling back change made into `jongo@1.4.0` and aligning over `bson4jackson@2.9.2`

**Comment by s-papa** [comment]
I met same issue using jackson sub-type and date-type. (bson4jackson@2.9.2)
bson4jackson's deserializers only  check BsonParser. but in specific case it passed JsonParserSequnce(JsonParser Helper) type instead of BsonParser.
Bson4jackson's deserializers need considering JsonParserSequence type.

**Comment by michel-kraemer** [comment]
I was finally able to reproduce and fix this issue. Version 2.11.0 has just been released.
